README.md
pkg/metadata/build_env_vars.go
pkg/metadata/collector.go
test/client_test.go
test/metadata_test.go

- update the readme
- Adding test

Update readme and add tests

---

README.md
pkg/metadata/build_env_vars.go
pkg/metadata/collector.go

- if the build system is overridabe people can set what they want
- update the readme accordingly

Add support for OVERRIDE_BUILDSYSTEM

---

.github/workflows/pr.yml
.github/workflows/release.yml
Makefile
test/bucket.yaml

On each PR and before release the integration test will run
In the future we will also validate the results on SaaS

Add integration test

---

.github/plugin_template.yaml
.github/workflows/release.yml
.goreleaser.yml
plugin.yaml

Add build assets for 
- linux
- amd64
- arm64
- darwin
- amd64
- arm64
- windows
- amd64
Update the plugin to use the selector to download the right one

Update build assets

---

cmd/aqua/main.go
pkg/metadata/collector.go

In this case scm-id will be the folder name

Add: support for none git folders

---

plugin.yaml

Fixing a typo for the plugin platform

fix the amd64 platform

---

.goreleaser.yml

The release will be statically compiled

To avoid platform issue for example in alpine image

---

cmd/aqua/main.go

In case assurance policy fail show error and add 1 as exit code

bugfix: panic on run error

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/aqua/main.go
pkg/buildClient/auth.go
pkg/buildClient/upload.go
pkg/processor/result_processor.go
pkg/scanner/local_scanner.go
pkg/scanner/scanner.go
test/process_results_test.go

Also fixing golangci lint errors

Add: golangci

---

cmd/aqua/main.go

Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>

feat(command): add quiet flag to base command

---

pkg/processor/result_processor.go
pkg/processor/result_processor_test.go
pkg/scanner/diff.go

In github we need fetch first the remote branch
Also added cleanup for base and head names in results

bugfix: github fetch first

---

pkg/scanner/diff.go

In GitHub trivy action container we need safe directory to run git fetch

(feat)trivy-action

---

.gitignore
.golangci.yml
Makefile
cmd/aqua/main.go

It is supported only in security-checks and created error when running "trivy config ."

fix(cmd): aqua config command was running secrets inside vuln type flag

---

.github/dependabot.yml

Dependabot will take the effort out of maintaining our dependencies and will send PRs for latest packages releases

feat(dependabot): maintaining dependencies

---

go.mod
go.sum
pkg/buildClient/comments.go

Also format comments markdown to support gitlab

chore(comments): include gitlab fix

---

go.mod
go.sum
pkg/buildClient/comments.go

resolved: SAAS-5236 bitbucket commenter

feat(commenter): bitbucket commenter

---

.golangci.yml
cmd/aqua/main.go
go.mod
go.sum
pkg/export/export.go
pkg/log/logger.go
pkg/processor/result_processor.go
pkg/proto/buildsecurity/buildsecurity.pb.go
pkg/proto/buildsecurity/buildsecurity.twirp.go
pkg/scanner/scanner.go
test/process_results_test.go

Used for Azure DevOps extension reports.
_This also fixes the dependency issues with fanal being moved into trivy._

feat: Add option to export assurance policy results

---

Makefile
plugin.yaml

This change eliminate the need to save the artifacts link in separate file and to do the actual downloads

improve artifacts links test

---

go.mod
go.sum
pkg/buildClient/comments.go
pkg/scanner/diff.go

resolves gh server action, and gh server with jenkins

GitHub enter action

---

README-dockerhub.md

add gradle limitations and support

add gradle non lock
